### PR TITLE
 add support for voltage, current, frequency and energy

### PR DESCRIPTION
**Pull request by selvakn**

### CODE REVIEW

**Comment by johanstokking** [comment]
@selvakn apologies for the late follow up and thanks for the clean PR.

Is this CayenneLPP 2.0?

**Comment by selvakn** [comment]
@johanstokking no worries.
This is not part of CayenneLPP yet, but based on IPSO, which cayenneLPP is based on.
Im trying to reach Eric Ptak from Cayenne to discuss about the right precision and have it added there. 

Meanwhile, having it in TTN would help my app.

**Comment by johanstokking** [comment]
Thanks for clarifying. We are keeping this repository consistent with CayenneLPP's specs for now. Until myDevices publishes a new release, we should not be rolling our own fork.

**Comment by aparcar** [comment]
It's been some time, any update on Cayenne supporting more IPSO formats? Other libraries [moved on](https://github.com/ElectronicCats/CayenneLPP/blob/master/API.md) and added them, including a TTN compatible [decoders script](https://github.com/ElectronicCats/CayenneLPP/blob/master/decoders/decoder.js).

**Comment by johanstokking** [comment]
That's the problem with CayenneLPP really; forks with new fields.

We keep https://github.com/myDevicesIoT/CayenneLPP as authoritive source.

**Pull request closed without merging**
